name = "KiteViewers"
uuid = "2e593061-95e7-45e4-95f4-df0491f2e601"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.4.11"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Joysticks = "82f05805-4863-42dc-b1a7-0852bd62c632"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Timers = "21f18d07-b854-4dab-86f0-c15a3821819a"

[compat]
FileIO = "1"
GLMakie = "~0.9"
GeometryBasics = "0.4.10"
Joysticks = "0.1.2, 0.1.4"
KiteUtils = "0.6.3"
Parameters = "0.12"
Pkg = "1.9, 1.10"
PrecompileTools = "1.2"
Reexport = "1"
Rotations = "1.2, 1.3"
StaticArrays = "~1.9"
Timers = "0.1.5"
julia = "1.9, 1.10"

[extras]
KiteModels = "b94af626-7959-4878-9336-2adc27959007"
KitePodModels = "9de5dc81-f971-414a-927b-652b2f41c539"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "KiteModels", "PyPlot", "KitePodModels", "PackageCompiler", "Plots"]
